"use client";
import React, { useState, useEffect } from "react";

const LISTA_PALAVRAS = [
  "REACT", "JAVASCRIPT", "NEXTJS", "COMPONENTE", "HOOKS", "ESTADO", "PROPRIEDADES",
  "BACKEND", "FRONTEND", "NODE", "BANCO", "API", "SERVIDOR", "CLIENTE", "CSS",
  "HTML", "FUNCAO", "OBJETO", "ARRAY", "VARIAVEL", "CONSTANTE", "ASYNC",
  "AWAIT", "PROMISE", "STRING", "NUMERO", "BOOLEAN", "IMPORT", "EXPORT",
  "ROTAS", "PROJETO", "DEPLOY", "NAVEGADOR", "PACOTE", "BIBLIOTECA",
  "FRAMEWORK", "MODULO", "EVENTO", "ESTRUTURA", "FORCA"
];
